# SUDOKU
# THIS PROJECT LOADS A SUDOKU BOARD FROM A TEXT FILE AND ALLOWS THE USER
# TO ATTEMPT TO SOLVE THE PUZZLE, OR TO AUTOMATICALLY SOLVE IT AT ANY
# GIVEN TIME DURING THE GAME. THE USER CAN ALSO SAVE THE GAME AND
# RESUME AT ANY TIME

from game import *

def main():
	game = Game()
	game.play()

main()